# Generated by Django 4.0.6 on 2022-08-10 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acpm', '0002_alter_user_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='EN_Название'),
        ),
        migrations.AlterField(
            model_name='education',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='KZ_Название'),
        ),
        migrations.AlterField(
            model_name='education',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='RU_Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='EN_Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='KZ_Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='RU_Название'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='EN_Название'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='KZ_Название'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='RU_Название'),
        ),
        migrations.AlterField(
            model_name='society',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='EN_Название'),
        ),
        migrations.AlterField(
            model_name='society',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='KZ_Название'),
        ),
        migrations.AlterField(
            model_name='society',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='RU_Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 10, 14, 47, 8, 118878, tzinfo=utc), verbose_name='Подписка действительна до'),
        ),
    ]
