# Generated by Django 4.0.6 on 2022-08-10 19:10

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acpm', '0006_alter_user_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='language',
        ),
        migrations.RemoveField(
            model_name='index',
            name='text',
        ),
        migrations.RemoveField(
            model_name='index',
            name='title',
        ),
        migrations.AddField(
            model_name='index',
            name='en_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текст на английском'),
        ),
        migrations.AddField(
            model_name='index',
            name='en_title',
            field=models.CharField(default='', max_length=50, verbose_name='Название на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='kz_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текст на казахском'),
        ),
        migrations.AddField(
            model_name='index',
            name='kz_title',
            field=models.CharField(default='', max_length=50, verbose_name='Название на казахском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='ru_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текст на русском'),
        ),
        migrations.AddField(
            model_name='index',
            name='ru_title',
            field=models.CharField(default='', max_length=50, verbose_name='Название на русском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='en_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на английском'),
        ),
        migrations.AlterField(
            model_name='education',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='education',
            name='kz_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на казахском'),
        ),
        migrations.AlterField(
            model_name='education',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='Название на  казахском'),
        ),
        migrations.AlterField(
            model_name='education',
            name='ru_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на русском'),
        ),
        migrations.AlterField(
            model_name='education',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='en_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на английском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kz_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на казахском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='Название на  казахском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ru_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на русском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='en_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на английском'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='kz_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на казахском'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='Название на  казахском'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='ru_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на русском'),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='society',
            name='en_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на английском'),
        ),
        migrations.AlterField(
            model_name='society',
            name='en_title',
            field=models.CharField(max_length=100, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='society',
            name='kz_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на казахском'),
        ),
        migrations.AlterField(
            model_name='society',
            name='kz_title',
            field=models.CharField(max_length=100, verbose_name='Название на  казахском'),
        ),
        migrations.AlterField(
            model_name='society',
            name='ru_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст на русском'),
        ),
        migrations.AlterField(
            model_name='society',
            name='ru_title',
            field=models.CharField(max_length=100, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 10, 19, 9, 45, 401084, tzinfo=utc), verbose_name='Подписка действительна до'),
        ),
    ]
