# Generated by Django 4.0.6 on 2022-08-10 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acpm', '0007_remove_index_language_remove_index_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube_url_event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='youtube_url_news',
            name='news',
        ),
        migrations.RemoveField(
            model_name='youtube_url_protocols',
            name='protocols',
        ),
        migrations.RemoveField(
            model_name='youtube_url_society',
            name='society',
        ),
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 10, 19, 22, 7, 808194, tzinfo=utc), verbose_name='Подписка действительна до'),
        ),
        migrations.DeleteModel(
            name='Youtube_Url_Education',
        ),
        migrations.DeleteModel(
            name='Youtube_Url_Event',
        ),
        migrations.DeleteModel(
            name='Youtube_Url_News',
        ),
        migrations.DeleteModel(
            name='Youtube_Url_Protocols',
        ),
        migrations.DeleteModel(
            name='Youtube_Url_Society',
        ),
    ]
