# Generated by Django 4.0.6 on 2022-08-10 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acpm', '0008_remove_youtube_url_event_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='en_announcement',
            field=models.CharField(default='', max_length=100, verbose_name='Аннонс на английском'),
        ),
        migrations.AddField(
            model_name='event',
            name='kz_announcement',
            field=models.CharField(default='', max_length=100, verbose_name='Аннонс на казахском'),
        ),
        migrations.AddField(
            model_name='event',
            name='ru_announcement',
            field=models.CharField(default='', max_length=100, verbose_name='Аннонс на русском'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 10, 19, 36, 37, 63259, tzinfo=utc), verbose_name='Подписка действительна до'),
        ),
    ]
