# Generated by Django 4.0.6 on 2022-08-16 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acpm', '0010_alter_user_expiration_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Conference',
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Конференция', 'verbose_name_plural': 'Конференция'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Меропрития', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 16, 12, 30, 41, 279594, tzinfo=utc), verbose_name='Подписка действительна до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер Телефона'),
        ),
    ]
